- id: '1775937452663'
  alias: Sync MA Playlists to ESP32
  triggers:
  - event: start
    trigger: homeassistant
  - hours: /6
    trigger: time_pattern
  actions:
  - action: pyscript.sync_ma_playlists
    data:
      config_entry_id: 01JEC8WMSGZRNN2YRA7HCJ49C8
      limit: 50
- id: '1776285228504'
  alias: Sync MA Queue on track change ESP32
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.jbl_bar_91_true_2
    attribute: media_title
  actions:
  - delay:
      seconds: 3
  - action: pyscript.sync_ma_queue
    metadata: {}
    data:
      entity_id: media_player.jbl_bar_91_true_2
