#include "panel_web.h"

#include "json_helpers.h"

#include <libsoup/soup.h>

#include <string.h>

/* The whole editor is one page compiled into the binary. The tablet is often
 * on a network with no route out of the house, so nothing in it may be
 * fetched from anywhere. */
#define PANEL_WEB_EDITOR_RESOURCE "/com/vahac/t560/editor.html"

/* What each skin looks like, one image per skin this build draws. They are
 * static pictures compiled in beside the editor rather than a live preview:
 * drawing one would mean a second implementation of every skin, in
 * JavaScript, kept in step with panel_ui.c by hand. Generated by
 * tools/make-skin-previews.py. */
#define PANEL_WEB_SKIN_PREFIX "/skins/"
#define PANEL_WEB_SKIN_SUFFIX ".png"
#define PANEL_WEB_SKIN_RESOURCE "/com/vahac/t560/skins/%s.png"

/* What a card icon is addressed as. The identifier after it is compared with
 * the catalog the integration publishes and never used to address anything;
 * nothing here becomes a resource path or a filename. No extension: the
 * paired ESP32 firmware serves the same editor page out of a different image
 * format, so the page asks for the icon rather than for a file. */
#define PANEL_WEB_ICON_PREFIX "/icons/"

/* A layout of a hundred cards is a few kilobytes. This is the ceiling on what
 * the editor may PUT, and it is the same order as the one Home Assistant
 * applies to the copy it stores: a body over it is refused before it is
 * read. */
#define PANEL_WEB_MAX_BODY 16384

struct _PanelWeb {
    SoupServer *server;
    PanelWebCallbacks callbacks;
    gpointer user_data;
    guint port;
    gchar *url;
};

/* One in-flight restore. The HTTP request it answers is paused while Home
 * Assistant is asked, so the main loop keeps running and the interface keeps
 * drawing: nothing here ever blocks the GTK thread. */
typedef struct {
    PanelWeb *web;
    SoupServerMessage *message;
} PanelWebRestore;

static void respond_json(SoupServerMessage *message, guint status,
                         const gchar *json)
{
    soup_server_message_set_status(message, status, NULL);
    soup_server_message_set_response(message, "application/json",
                                     SOUP_MEMORY_COPY, json, strlen(json));
}

static void respond_error(SoupServerMessage *message, guint status,
                          const gchar *text)
{
    JsonBuilder *builder = json_builder_new();

    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "error");
    json_builder_add_string_value(builder, text);
    json_builder_end_object(builder);

    gchar *json = json_builder_to_string(builder);
    respond_json(message, status, json);
    g_free(json);
    g_object_unref(builder);
}

static void respond_ok(SoupServerMessage *message)
{
    respond_json(message, SOUP_STATUS_OK, "{\"status\":\"ok\"}");
}

/* Every route answers exactly one method. Anything else is refused rather
 * than quietly treated as a GET, so that a mistake in a client is visible. */
static gboolean method_is(SoupServerMessage *message, const gchar *method)
{
    return g_strcmp0(soup_server_message_get_method(message), method) == 0;
}

static gchar *read_body(SoupServerMessage *message, gchar **error_message)
{
    SoupMessageBody *body = soup_server_message_get_request_body(message);

    if (body == NULL || body->length == 0) {
        *error_message = g_strdup("The request has no body.");
        return NULL;
    }
    if (body->length > PANEL_WEB_MAX_BODY) {
        *error_message = g_strdup("The layout is too large.");
        return NULL;
    }
    return g_strndup(body->data, (gsize)body->length);
}

/* ------------------------------------------------------------------ routes */

static void handle_editor(PanelWeb *web, SoupServerMessage *message)
{
    GBytes *page = g_resources_lookup_data(PANEL_WEB_EDITOR_RESOURCE,
                                           G_RESOURCE_LOOKUP_FLAGS_NONE, NULL);

    (void)web;
    if (page == NULL) {
        respond_error(message, SOUP_STATUS_INTERNAL_SERVER_ERROR,
                      "The editor is missing from this build.");
        return;
    }

    gsize length = 0;
    const gchar *data = g_bytes_get_data(page, &length);

    soup_server_message_set_status(message, SOUP_STATUS_OK, NULL);
    soup_server_message_set_response(message, "text/html; charset=utf-8",
                                     SOUP_MEMORY_COPY, data, length);
    g_bytes_unref(page);
}

/* One skin preview.
 *
 * The name in the path is never used to build a resource path directly. It is
 * put through panel_player_skin_from_string and compared with the round trip,
 * exactly as handle_put_skin does, so only a name this build actually draws
 * can reach g_resources_lookup_data and "../" cannot. */
static void handle_skin_preview(PanelWeb *web, SoupServerMessage *message,
                                const gchar *path)
{
    const gchar *tail = path + strlen(PANEL_WEB_SKIN_PREFIX);
    gsize length = strlen(tail);
    gsize suffix = strlen(PANEL_WEB_SKIN_SUFFIX);

    (void)web;
    if (length <= suffix ||
        g_strcmp0(tail + length - suffix, PANEL_WEB_SKIN_SUFFIX) != 0) {
        soup_server_message_set_status(message, SOUP_STATUS_NOT_FOUND, NULL);
        return;
    }

    gchar *name = g_strndup(tail, length - suffix);
    PanelPlayerSkin skin = panel_player_skin_from_string(name);
    if (g_strcmp0(panel_player_skin_to_string(skin), name) != 0) {
        soup_server_message_set_status(message, SOUP_STATUS_NOT_FOUND, NULL);
        g_free(name);
        return;
    }

    gchar *resource = g_strdup_printf(PANEL_WEB_SKIN_RESOURCE, name);
    GBytes *image = g_resources_lookup_data(resource,
                                            G_RESOURCE_LOOKUP_FLAGS_NONE,
                                            NULL);
    g_free(resource);
    g_free(name);

    if (image == NULL) {
        /* A skin this build draws but carries no picture for. The editor
         * falls back to the name alone rather than showing a broken image. */
        soup_server_message_set_status(message, SOUP_STATUS_NOT_FOUND, NULL);
        return;
    }

    gsize size = 0;
    const gchar *data = g_bytes_get_data(image, &size);

    soup_server_message_set_status(message, SOUP_STATUS_OK, NULL);
    soup_server_message_set_response(message, "image/png", SOUP_MEMORY_COPY,
                                     data, size);
    /* Compiled in, so it changes only when the panel is rebuilt: worth
     * caching for the life of the page rather than fetching per render. */
    soup_message_headers_replace(
        soup_server_message_get_response_headers(message), "Cache-Control",
        "max-age=86400");
    g_bytes_unref(image);
}

/* The registry, straight out of the payload the panel already holds. The
 * editor never reaches Home Assistant and this route never does either. */
static void handle_entities(PanelWeb *web, SoupServerMessage *message)
{
    const PanelLayout *layout = web->callbacks.layout(web->user_data);
    JsonBuilder *builder = json_builder_new();

    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "entities");
    json_builder_begin_array(builder);
    guint count = layout != NULL && layout->entities != NULL
                      ? layout->entities->len
                      : 0;
    for (guint i = 0; i < count; i++) {
        const PanelEntity *entity = g_ptr_array_index(layout->entities, i);

        json_builder_begin_object(builder);
        json_builder_set_member_name(builder, "rid");
        json_builder_add_string_value(builder, entity->rid);
        json_builder_set_member_name(builder, "entity");
        json_builder_add_string_value(builder, entity->entity);
        json_builder_set_member_name(builder, "name");
        json_builder_add_string_value(builder, entity->name);
        /* What the person chose for this element, so that the editor shows
         * the choice rather than guessing at it from the picture on
         * screen. Empty means they chose none and the domain decides. */
        json_builder_set_member_name(builder, "icon");
        json_builder_add_string_value(
            builder, entity->icon != NULL ? entity->icon : "");
        json_builder_set_member_name(builder, "domain");
        json_builder_add_string_value(builder, entity->domain);
        json_builder_set_member_name(builder, "brightness");
        json_builder_add_boolean_value(builder, entity->brightness);
        json_builder_set_member_name(builder, "color_temp");
        json_builder_add_boolean_value(builder, entity->color_temperature);
        json_builder_set_member_name(builder, "target_temperature");
        json_builder_add_boolean_value(builder, entity->target_temperature);
        json_builder_set_member_name(builder, "position");
        json_builder_add_boolean_value(builder, entity->position);
        json_builder_set_member_name(builder, "stop");
        json_builder_add_boolean_value(builder, entity->stoppable);
        json_builder_end_object(builder);
    }
    json_builder_end_array(builder);

    /* The artwork the Media Controller integration publishes, so the editor
     * offers exactly what a card can be given rather than a list written
     * down twice. It is the integration's catalog and not this build's
     * resources: adding a picture there must not mean rebuilding the panel,
     * and the paired ESP32 across the house has to be offered the same list.
     *
     * Empty before the catalog has been fetched, and empty for good on a
     * panel that has never paired. The editor then offers Automatic alone,
     * which is the honest answer: there is nothing else this panel could be
     * told to draw. */
    PanelCards *cards = web->callbacks.cards(web->user_data);
    json_builder_set_member_name(builder, "icons");
    json_builder_begin_array(builder);
    guint icons = panel_cards_catalog_size(cards);
    for (guint i = 0; i < icons; i++) {
        json_builder_begin_object(builder);
        json_builder_set_member_name(builder, "id");
        json_builder_add_string_value(builder,
                                      panel_cards_catalog_id(cards, i));
        json_builder_set_member_name(builder, "label");
        json_builder_add_string_value(builder,
                                      panel_cards_catalog_label(cards, i));
        json_builder_end_object(builder);
    }
    json_builder_end_array(builder);

    /* What the editor may not exceed, so the limit is enforced in one place
     * and read in the other rather than written down twice. */
    json_builder_set_member_name(builder, "limits");
    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "name");
    json_builder_add_int_value(builder, PANEL_CARD_NAME_MAX_CHARS);
    json_builder_end_object(builder);

    /* How the last card edit ended. It lives here, on the route that answers
     * "what is this panel's situation", because the write reaches Home
     * Assistant asynchronously and cannot be answered inside the request
     * that asked for it — the same shape the restore already has. */
    PanelCardWriteState write = panel_cards_write_state(cards);
    json_builder_set_member_name(builder, "card");
    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "state");
    json_builder_add_string_value(
        builder, write == PANEL_CARD_WRITE_PENDING  ? "pending"
                 : write == PANEL_CARD_WRITE_OK     ? "ok"
                 : write == PANEL_CARD_WRITE_FAILED ? "failed"
                                                    : "idle");
    json_builder_set_member_name(builder, "message");
    json_builder_add_string_value(builder,
                                  panel_cards_write_message(cards));
    json_builder_end_object(builder);

    json_builder_set_member_name(builder, "grid");
    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "cols");
    json_builder_add_int_value(builder, PANEL_GRID_COLUMNS);
    json_builder_set_member_name(builder, "rows");
    json_builder_add_int_value(builder, PANEL_GRID_ROWS);
    json_builder_end_object(builder);
    json_builder_end_object(builder);

    gchar *json = json_builder_to_string(builder);
    respond_json(message, SOUP_STATUS_OK, json);
    g_free(json);
    g_object_unref(builder);
}

static void handle_get_layout(PanelWeb *web, SoupServerMessage *message)
{
    const PanelGrid *grid = web->callbacks.grid(web->user_data);

    if (grid == NULL) {
        respond_error(message, SOUP_STATUS_SERVICE_UNAVAILABLE,
                      "The panel has not built its room page yet.");
        return;
    }

    gchar *json = panel_grid_to_json(grid);
    respond_json(message, SOUP_STATUS_OK, json);
    g_free(json);
}

static void handle_put_layout(PanelWeb *web, SoupServerMessage *message)
{
    gchar *failure = NULL;
    gchar *body = read_body(message, &failure);

    if (body == NULL) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST, failure);
        g_free(failure);
        return;
    }

    guint dropped = 0;
    PanelGrid *grid = panel_grid_parse(body, -1, &dropped, &failure);
    g_free(body);
    if (grid == NULL) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST, failure);
        g_free(failure);
        return;
    }
    /* A layout that lost cards on the way in is refused rather than saved as
     * something the editor did not ask for. The editor already refuses to
     * place a card that does not fit, so this only catches another client. */
    if (dropped > 0) {
        panel_grid_free(grid);
        gchar *text = g_strdup_printf(
            "%u card(s) are outside the grid or overlap another card.",
            dropped);
        respond_error(message, SOUP_STATUS_BAD_REQUEST, text);
        g_free(text);
        return;
    }

    gboolean backed_up = FALSE;
    if (!web->callbacks.save_grid(grid, &backed_up, &failure,
                                  web->user_data)) {
        panel_grid_free(grid);
        respond_error(message, SOUP_STATUS_INTERNAL_SERVER_ERROR, failure);
        g_free(failure);
        return;
    }

    JsonBuilder *builder = json_builder_new();
    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "status");
    json_builder_add_string_value(builder, "ok");
    /* Whether the copy reached Home Assistant is reported, never enforced: a
     * layout that is on the panel is saved, whatever Home Assistant did. */
    json_builder_set_member_name(builder, "backup");
    json_builder_add_boolean_value(builder, backed_up);
    json_builder_end_object(builder);

    gchar *json = json_builder_to_string(builder);
    respond_json(message, SOUP_STATUS_OK, json);
    g_free(json);
    g_object_unref(builder);
}

static void restore_ready(const gchar *layout, const gchar *error_message,
                          gpointer request)
{
    PanelWebRestore *restore = request;
    SoupServerMessage *message = restore->message;
    PanelWeb *web = restore->web;

    if (layout == NULL) {
        respond_error(message, SOUP_STATUS_BAD_GATEWAY,
                      error_message != NULL
                          ? error_message
                          : "Home Assistant holds no copy of this layout.");
        goto done;
    }

    gchar *failure = NULL;
    guint dropped = 0;
    PanelGrid *grid = panel_grid_parse(layout, -1, &dropped, &failure);
    if (grid == NULL) {
        respond_error(message, SOUP_STATUS_BAD_GATEWAY, failure);
        g_free(failure);
        goto done;
    }

    gboolean backed_up = FALSE;
    if (!web->callbacks.save_grid(grid, &backed_up, &failure,
                                  web->user_data)) {
        panel_grid_free(grid);
        respond_error(message, SOUP_STATUS_INTERNAL_SERVER_ERROR, failure);
        g_free(failure);
        goto done;
    }
    respond_ok(message);

done:
    soup_server_message_unpause(message);
    g_object_unref(message);
    g_free(restore);
}

/* The one route that has to reach Home Assistant. The request is paused
 * rather than waited on, so the GTK main loop keeps drawing while the answer
 * is in flight. */
static void handle_delete_layout(PanelWeb *web, SoupServerMessage *message)
{
    PanelWebRestore *restore = g_new0(PanelWebRestore, 1);

    restore->web = web;
    restore->message = g_object_ref(message);
    soup_server_message_pause(message);
    web->callbacks.restore(restore_ready, restore, web->user_data);
}

static void handle_skins(PanelWeb *web, SoupServerMessage *message)
{
    const PanelLayout *layout = web->callbacks.layout(web->user_data);
    JsonBuilder *builder = json_builder_new();

    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "skins");
    json_builder_begin_array(builder);
    for (guint i = 0; i < PANEL_PLAYER_SKIN_COUNT; i++)
        json_builder_add_string_value(builder, panel_player_skin_to_string(i));
    json_builder_end_array(builder);

    /* The skin on screen, which is always one of the names above: Home
     * Assistant's choice once somebody has made one, and the config.ini
     * fallback until then. Reporting what Home Assistant last said instead
     * would leave the picker blank on a panel that has never been given a
     * skin, and stale on one that has just been given a new one. */
    json_builder_set_member_name(builder, "current");
    json_builder_add_string_value(
        builder, panel_player_skin_to_string(web->callbacks.skin(
                     web->user_data)));
    /* Whether this panel was told which entity holds the skin. Without one
     * there is nothing to write, and the editor greys the control. */
    json_builder_set_member_name(builder, "writable");
    json_builder_add_boolean_value(
        builder, layout != NULL && layout->skin_select_entity != NULL);
    json_builder_end_object(builder);

    gchar *json = json_builder_to_string(builder);
    respond_json(message, SOUP_STATUS_OK, json);
    g_free(json);
    g_object_unref(builder);
}

/* Calls select.select_option on this panel's own skin select and nothing
 * else. The name is checked against the skins this build draws before it is
 * sent, so this route cannot be used to write an arbitrary value into an
 * arbitrary entity. */
static void handle_put_skin(PanelWeb *web, SoupServerMessage *message)
{
    gchar *failure = NULL;
    gchar *body = read_body(message, &failure);

    if (body == NULL) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST, failure);
        g_free(failure);
        return;
    }

    JsonParser *parser = json_parser_new();
    GError *error = NULL;
    const gchar *requested = NULL;

    if (json_parser_load_from_data(parser, body, -1, &error) &&
        json_parser_get_root(parser) != NULL &&
        JSON_NODE_HOLDS_OBJECT(json_parser_get_root(parser))) {
        requested = json_object_string(
            json_node_get_object(json_parser_get_root(parser)), "skin", NULL);
    }
    g_clear_error(&error);
    g_free(body);

    if (requested == NULL || *requested == '\0') {
        respond_error(message, SOUP_STATUS_BAD_REQUEST,
                      "No skin was named.");
        g_object_unref(parser);
        return;
    }

    /* An unknown name is refused rather than passed on. panel_player_skin_
     * from_string answers with the default for anything it does not know, so
     * comparing the round trip is what tells a real name from a typo. */
    PanelPlayerSkin skin = panel_player_skin_from_string(requested);
    if (g_strcmp0(panel_player_skin_to_string(skin), requested) != 0) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST,
                      "This panel does not draw that skin.");
        g_object_unref(parser);
        return;
    }

    if (!web->callbacks.select_skin(requested, &failure, web->user_data)) {
        respond_error(message, SOUP_STATUS_BAD_GATEWAY, failure);
        g_free(failure);
        g_object_unref(parser);
        return;
    }
    respond_ok(message);
    g_object_unref(parser);
}

/* One catalog picture, for the editor page.
 *
 * It is served out of what the panel has already downloaded for its own
 * cards, so there is no proxy here and no second fetch, and the panel's Home
 * Assistant token never comes anywhere near the browser. The identifier in
 * the path is compared with the catalog and never used to build a resource
 * path, a filename or a URL. A picture that has not arrived yet is a 404, and
 * the editor drops the image and keeps the name — exactly what it already
 * does for a skin this build carries no picture of. */
static void handle_icon(PanelWeb *web, SoupServerMessage *message,
                        const gchar *path)
{
    const gchar *id = path + strlen(PANEL_WEB_ICON_PREFIX);
    PanelCards *cards = web->callbacks.cards(web->user_data);

    if (!panel_card_icon_id_is_sane(id) ||
        !panel_cards_publishes(cards, id)) {
        soup_server_message_set_status(message, SOUP_STATUS_NOT_FOUND, NULL);
        return;
    }

    GBytes *image = panel_cards_image(cards, id);
    if (image == NULL) {
        soup_server_message_set_status(message, SOUP_STATUS_NOT_FOUND, NULL);
        return;
    }

    gsize size = 0;
    const gchar *data = g_bytes_get_data(image, &size);

    soup_server_message_set_status(message, SOUP_STATUS_OK, NULL);
    soup_server_message_set_response(message, "image/png", SOUP_MEMORY_COPY,
                                     data, size);
    /* The pictures change only when the integration is upgraded, and the
     * editor asks for one per catalog row on every render. */
    soup_message_headers_replace(
        soup_server_message_get_response_headers(message), "Cache-Control",
        "max-age=3600");
}

/* The display name and icon of one card.
 *
 * This is the only route that ends in a write to Home Assistant's own data,
 * and it is deliberately the narrowest one here. It can change the name and
 * the picture of an element **this panel already draws**, and there is no
 * path through it that names an entity, calls a service, adds an element, or
 * reaches anything the registry does not already carry. Everything it accepts
 * is checked here and again by the integration, which is the side that
 * actually owns the registry.
 *
 * A key that is absent means "leave this alone" and a key that is present
 * means "set it to this, including to nothing". The difference matters: a
 * card whose name field simply shows the Home Assistant entity's own name
 * must not have that name stored as a custom one because somebody changed its
 * icon, or it would stop following the entity through a rename. */
static void handle_post_card(PanelWeb *web, SoupServerMessage *message)
{
    gchar *failure = NULL;
    gchar *body = read_body(message, &failure);

    if (body == NULL) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST, failure);
        g_free(failure);
        return;
    }

    JsonParser *parser = json_parser_new();
    GError *error = NULL;
    JsonObject *object = NULL;

    if (json_parser_load_from_data(parser, body, -1, &error) &&
        json_parser_get_root(parser) != NULL &&
        JSON_NODE_HOLDS_OBJECT(json_parser_get_root(parser))) {
        object = json_node_get_object(json_parser_get_root(parser));
    }
    g_clear_error(&error);
    g_free(body);

    if (object == NULL) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST,
                      "The request is not a JSON object.");
        g_object_unref(parser);
        return;
    }

    const gchar *rid = json_object_string(object, "rid", NULL);
    gboolean has_name = json_object_has_member(object, "name");
    gboolean has_icon = json_object_has_member(object, "icon");

    if (rid == NULL || *rid == '\0') {
        respond_error(message, SOUP_STATUS_BAD_REQUEST,
                      "That is not a registry identifier.");
        g_object_unref(parser);
        return;
    }
    if (!has_name && !has_icon) {
        respond_error(message, SOUP_STATUS_BAD_REQUEST,
                      "There is nothing to change.");
        g_object_unref(parser);
        return;
    }

    /* The element has to be one this panel is already drawing. That single
     * check is what stops this route being a way to write into a registry
     * the caller knows nothing about. */
    const PanelLayout *layout = web->callbacks.layout(web->user_data);
    if (panel_layout_find_entity(layout, rid) == NULL) {
        respond_error(message, SOUP_STATUS_NOT_FOUND,
                      "This panel draws no such card.");
        g_object_unref(parser);
        return;
    }

    gchar *name = NULL;
    if (has_name) {
        PanelCardNameResult result = panel_card_name_normalize(
            json_object_string(object, "name", ""), &name);
        if (result != PANEL_CARD_NAME_OK) {
            respond_error(message, SOUP_STATUS_BAD_REQUEST,
                          panel_card_name_error(result));
            g_object_unref(parser);
            return;
        }
    }

    const gchar *icon = NULL;
    if (has_icon) {
        icon = json_object_string(object, "icon", "");
        if (icon == NULL)
            icon = "";
        /* Empty is "choose automatically" and is always allowed. Anything
         * else has to be something the integration says it publishes. */
        if (*icon != '\0' &&
            !panel_cards_publishes(web->callbacks.cards(web->user_data),
                                   icon)) {
            respond_error(message, SOUP_STATUS_BAD_REQUEST,
                          "Home Assistant does not publish that icon.");
            g_free(name);
            g_object_unref(parser);
            return;
        }
    }

    if (!web->callbacks.write_card(rid, name, icon, &failure,
                                   web->user_data)) {
        respond_error(message, SOUP_STATUS_BAD_GATEWAY, failure);
        g_free(failure);
        g_free(name);
        g_object_unref(parser);
        return;
    }
    g_free(name);
    g_object_unref(parser);

    JsonBuilder *builder = json_builder_new();
    json_builder_begin_object(builder);
    json_builder_set_member_name(builder, "status");
    json_builder_add_string_value(builder, "ok");
    /* Whether the change is on its way to Home Assistant is reported, never
     * enforced: a panel that has not paired yet still has an editor, and the
     * person using it should be told which of the two happened. */
    json_builder_set_member_name(builder, "synced");
    json_builder_add_boolean_value(builder, TRUE);
    json_builder_end_object(builder);

    gchar *json = json_builder_to_string(builder);
    respond_json(message, SOUP_STATUS_OK, json);
    g_free(json);
    g_object_unref(builder);
}

/* ----------------------------------------------------------------- routing */

static void handle_request(SoupServer *server, SoupServerMessage *message,
                           const char *path, GHashTable *query,
                           gpointer user_data)
{
    PanelWeb *web = user_data;

    (void)server;
    (void)query;

    /* Ten routes, and the table below is all of them. There is deliberately
     * no catch-all and no path that takes an entity, a service or a URL from
     * the caller: this server has no password, so what it cannot express is
     * the security model. The two routes that take a name from the caller —
     * the skin preview and the card picture — check it against what this
     * build actually has before it addresses anything, and neither builds a
     * path out of it. */
    if (g_strcmp0(path, "/") == 0) {
        if (!method_is(message, "GET")) {
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
            return;
        }
        handle_editor(web, message);
        return;
    }

    if (g_str_has_prefix(path, PANEL_WEB_SKIN_PREFIX)) {
        if (method_is(message, "GET"))
            handle_skin_preview(web, message, path);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    if (g_str_has_prefix(path, PANEL_WEB_ICON_PREFIX)) {
        if (method_is(message, "GET"))
            handle_icon(web, message, path);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    if (g_strcmp0(path, "/api/entities") == 0) {
        if (method_is(message, "GET"))
            handle_entities(web, message);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    if (g_strcmp0(path, "/api/layout") == 0) {
        if (method_is(message, "GET"))
            handle_get_layout(web, message);
        else if (method_is(message, "PUT"))
            handle_put_layout(web, message);
        else if (method_is(message, "DELETE"))
            handle_delete_layout(web, message);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    if (g_strcmp0(path, "/api/skins") == 0) {
        if (method_is(message, "GET"))
            handle_skins(web, message);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    if (g_strcmp0(path, "/api/card") == 0) {
        /* POST rather than PUT, unlike the layout and the skin beside it.
         * The paired ESP32 firmware serves the same editor page, and its
         * ESP-IDF web server registers handlers for GET, POST and OPTIONS
         * only: a PUT never reaches one there. Spelling this route the same
         * way on both is one fewer difference between two files that are
         * meant to stay the same page. */
        if (method_is(message, "POST"))
            handle_post_card(web, message);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    if (g_strcmp0(path, "/api/skin") == 0) {
        if (method_is(message, "PUT"))
            handle_put_skin(web, message);
        else
            soup_server_message_set_status(
                message, SOUP_STATUS_METHOD_NOT_ALLOWED, NULL);
        return;
    }

    soup_server_message_set_status(message, SOUP_STATUS_NOT_FOUND, NULL);
}

/* ------------------------------------------------------------- lifecycle */

/* The address a phone on the same network should use. The listener binds
 * every interface, so this only has to name one of them that is routable;
 * the hostname is the fallback when none can be read. */
static gchar *first_local_address(guint port)
{
    GSocketAddress *local = NULL;
    GSocket *socket = g_socket_new(G_SOCKET_FAMILY_IPV4,
                                   G_SOCKET_TYPE_DATAGRAM,
                                   G_SOCKET_PROTOCOL_UDP, NULL);
    gchar *url = NULL;

    if (socket != NULL) {
        /* Connecting a datagram socket sends nothing. It only asks the
         * kernel which of this machine's addresses it would route from,
         * which is the address a phone on that network can reach. */
        GInetAddress *probe = g_inet_address_new_from_string("192.168.1.1");
        GSocketAddress *target = g_inet_socket_address_new(probe, 53);

        if (g_socket_connect(socket, target, NULL, NULL))
            local = g_socket_get_local_address(socket, NULL);
        g_object_unref(target);
        g_object_unref(probe);
        g_object_unref(socket);
    }

    if (local != NULL) {
        GInetAddress *address = g_inet_socket_address_get_address(
            G_INET_SOCKET_ADDRESS(local));
        gchar *text = g_inet_address_to_string(address);

        if (text != NULL && !g_str_equal(text, "0.0.0.0"))
            url = g_strdup_printf("http://%s:%u/", text, port);
        g_free(text);
        g_object_unref(local);
    }

    if (url == NULL)
        url = g_strdup_printf("http://%s:%u/", g_get_host_name(), port);
    return url;
}

PanelWeb *panel_web_new(guint port, const PanelWebCallbacks *callbacks,
                        gpointer user_data, gchar **error_message)
{
    g_return_val_if_fail(callbacks != NULL, NULL);
    g_return_val_if_fail(error_message != NULL, NULL);

    PanelWeb *web = g_new0(PanelWeb, 1);
    GError *error = NULL;

    web->callbacks = *callbacks;
    web->user_data = user_data;
    web->port = port;
    web->server = soup_server_new("server-header", "t560-panel", NULL);
    soup_server_add_handler(web->server, "/", handle_request, web, NULL);

    if (!soup_server_listen_all(web->server, port, 0, &error)) {
        *error_message = g_strdup(error != NULL ? error->message
                                                : "unknown error");
        g_clear_error(&error);
        panel_web_free(web);
        return NULL;
    }

    web->url = first_local_address(port);
    return web;
}

void panel_web_free(PanelWeb *web)
{
    if (web == NULL)
        return;

    if (web->server != NULL) {
        soup_server_disconnect(web->server);
        g_object_unref(web->server);
    }
    g_free(web->url);
    g_free(web);
}

const gchar *panel_web_url(PanelWeb *web)
{
    return web != NULL ? web->url : NULL;
}
